config:
  name: "raspberry-pi"
  url: "raspberrypi.local"
  password: "raspberry"
  port: "22"
chip:
  digital-pins:
    - id: "gpio17"
      pin: 17
      value: 1
      direction: 1
      edge: 0
    - id: "gpio18"
      pin: 18
      value: 0
      direction: 0
      edge: 1
# analog-pins:
#   - id: "adc0"
#     pin: 0
#     value: 0
#     mode: 0
#     pull: 1
