config:
  device-name: "pi"
  mode: "ssh"
  url: "192.168.1.98"
  port: "22"
  username: "pi"
  auth-method: "password"
  password: "alesio1234"
  pool-size: 1
  max-retries: 3
  retry-delay: 2

chip:
  digital-pins: []

  pwm-pins:
    - id: "buzzer"
      pin: 18
      frequency: 1000
      duty-cycle: 0

  i2c-devices:
    - id: "weather"
      type: "bmp280"
      bus: 1
      address: "0x76"

mqtt:
  broker: "tcp://xxxxxx:1883"
  client-id: "pioneer-pi"
  topic: "pioneer"
  username: ""
  password: ""
  use-tls: false
  qos: 1
